### ISSUE TITLE
please provide uninstall script

### ISSUE THREAD

**Issue by krishnaTORQUE** [pcb2gcode/pcb2gcodeGUI#18]
please provide uninstall script
`sudo make uninstall` does not working on ubuntu

**Comment by eyal0** [comment]
I don't really support pcb2gcodeGUI.  It's quite old and pcb2gcode has lots of features that are newer than it.  Would you be able to use the CLI directly?

**Comment by the-snowwhite** [comment]
You need to run qmake first with the same PREFIX=<yourpath> as you used for installing, or you can do:

    which pcb2gcodeGUI

and the paste the reported file path after PREFIX=
