### ISSUE TITLE
Save and Load FILEARGS

### ISSUE THREAD

**Issue by ecanardi** [pcb2gcode/pcb2gcodeGUI#2]
Why don't you add the capability to load and save also the FILEARGS?

enrico

**Comment by corna** [comment]
It can be added easily, but why? I personally don't find it much useful

**Comment by ecanardi** [comment]
To be able to modify a previously saved configuration

**Comment by corna** [comment]
With the latest updates the workflow is much faster and selecting the input files is almost instant
