### ISSUE TITLE
can possible remove repeated lines?

### ISSUE THREAD

**Issue by ashokavarthanan** [pcb2gcode/pcb2gcodeGUI#24]
hi.
when I using "Extra Passes " the result G-code is more repeated lines.
can solve this?

<img width="866" alt="test_pcbtogcode" src="https://user-images.githubusercontent.com/54305413/184093172-3c611d9d-a548-437e-be84-470cc6241697.png">

when using "Extra Passes" normal pcb circuit more time waste for repeated lines when using .

**Comment by Holotronic** [comment]
@ashokavarthanan Pcb2gcodeGUI is just a frontend for pcb2gcode
the parameter is named extra-passes so try going to https://github.com/pcb2gcode/pcb2gcode to get your issue resolved

**Comment by the-snowwhite** [comment]
@ashokavarthanan Pcb2gcodeGUI is just a frontend for pcb2gcode
the parameter is named extra-passes so try going to https://github.com/pcb2gcode/pcb2gcode to get your issue resolved

**Comment by ashokavarthanan** [comment]
> @ashokavarthanan Pcb2gcodeGUI is just a frontend for pcb2gcode the parameter is named extra-passes so try going to https://github.com/pcb2gcode/pcb2gcode to get your issue resolved

Solved Thanks .
Pcb2gcode command line tool  Solved this.
