### ISSUE TITLE
pcb2gcode will crash without reason

### ISSUE THREAD

**Issue by Bastler100** [pcb2gcode/pcb2gcodeGUI#25]
Hello,
I use pcb2gcode some time and it works very well. At one time the program always crashes with this messages:
Importing front side... not specified.
Importing back side... DONE.
Importing outline... DONE.
Processing input files... 
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'Glib::FileError'
I use V1.3.2-1 Win64, I use only copper back, board outline and the drill-files.
Many thanks for every answer
Hans

**Comment by Holotronic** [comment]
@Bastler100 
You may want to try building a [newer windows version](https://github.com/pcb2gcode/pcb2gcodeGUI#build-on-windows
) with the latest [release](https://github.com/pcb2gcode/pcb2gcodeGUI/releases/tag/v1.3.3
)  ?

If its a bug for pcb2gcode (as you write)please submit your issue here: https://github.com/pcb2gcode/pcb2gcode

**Comment by Bastler100** [comment]
I dont know if the mistake is in the pcb2gcode or  in the gui. Does someone know what version of pcb2gcode and gui will work
with Win7pro?

**Comment by eyal0** [comment]
The latest pcb2gcode ought to compile on Windows but I'm unable to test it because I don't use Windows!

If you know how to compile and you want to try, I'll assist you with any errors.

**Comment by Bastler100** [comment]
Hello eyal0,
many thanks for your answer. I test the pcb2gcode with gerber files from an other pcb-layouter and it works very well. I will now
look for the reason why my pcb-layout-software produces at one time other gerber-files.

**Comment by Bastler100** [comment]
Hello,
pcb2gcode works now correct. The voronoi modus works in the newer version very well. In the outline gerberfile was a problem
with the boardcontour.

**Comment by eyal0** [comment]
I fixed a bug in board contour once where one of the tools was creating paths that were almost but not exactly closed.

Anyway, if it's working, close the bug?

**Comment by the-snowwhite** [comment]
@Bastler100 
Im glad that you solved your issue and thanks for following up and reporting back.
@eyal0  Thanks for keeping an eye on this thread
I'll close now
