### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by kosme** [pcb2gcode/pcb2gcodeGUI#5]
Just pulled the latest commits and I get the following error when building:

In file included from mainwindow.h:39:0,
                 from main.cpp:20:
argaction.h: In member function ‘bool argAction::setValue(QString, QString)’:
argaction.h:92:9: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto pos = objects.find(key);
         ^
argaction.h:92:14: error: ‘pos’ does not name a type
         auto pos = objects.find(key);
              ^
argaction.h:94:13: error: ‘pos’ was not declared in this scope
         if (pos != objects.end())
             ^
argaction.h: At global scope:
argaction.h:90:17: warning: unused parameter ‘key’ [-Wunused-parameter]
     inline bool setValue(const QString key, const QString value)
                 ^
make: **\* [main.o] Error 1

**Comment by corna** [comment]
Try to add

```
 CONFIG += c++11
```

at the end of pcb2gcodeGUI.pro, re-run qmake and rebuild

**Comment by kosme** [comment]
That fixes it but now shows a new error.
In file included from mainwindow.cpp:21:0:
ui_mainwindow.h: In member function ‘void Ui_MainWindow::setupUi(QMainWindow_)’:
ui_mainwindow.h:279:21: error: ‘class QTabWidget’ has no member named ‘setTabBarAutoHide’
         optionsTab->setTabBarAutoHide(false);
                     ^
make: *_\* [mainwindow.o] Error 1
It appears that setTabBatAutoHide is a property introduced in QT5.4 and current package managers install QT5.2.1

**Comment by corna** [comment]
With commit 280cf3a1c29b794ad68bfd9426c3132e10eccee0 I've removed the C++11 code, and with 832e260d0e81afe09fab98e2e3e1625bd6c5a8ab I've removed the ui properties unsupported by Qt 5.0.0
Can you pull the latest changes and try again?

**Comment by kosme** [comment]
It now compiles nicely. The only thing, really small detail, is that now the GUI version is ahead of the CLI version.

**Comment by corna** [comment]
I know, I'm going to release the new CLI version very soon
